"""Shared constants for the Public Contract Closure Gate arm."""

from __future__ import annotations

CONTRACT_CLOSURE_GATE_ENV = "FEATURELIFTBENCH_CONTRACT_CLOSURE_GATE"
CONTRACT_CLOSURE_GATE_LITE_ENV = "FEATURELIFTBENCH_CONTRACT_CLOSURE_GATE_LITE"
CONTRACT_CLOSURE_GATE_LITE_V1_ENV = (
    "FEATURELIFTBENCH_CONTRACT_CLOSURE_GATE_LITE_V1_FROZEN"
)
CONTRACT_CLOSURE_GATE_V3_ENV = "FEATURELIFTBENCH_CONTRACT_CLOSURE_GATE_V3"
CONTRACT_CLOSURE_PHASE_ENV = "FEATURELIFTBENCH_CONTRACT_CLOSURE_PHASE"
PRIMARY_TOKEN_LIMIT_ENV = "FEATURELIFTBENCH_CONTRACT_CLOSURE_PRIMARY_TOKEN_LIMIT"
REPAIR_TOKEN_LIMIT_ENV = "FEATURELIFTBENCH_CONTRACT_CLOSURE_REPAIR_TOKEN_LIMIT"
PRIMARY_MAX_STEPS_ENV = "FEATURELIFTBENCH_CONTRACT_CLOSURE_PRIMARY_MAX_STEPS"
REPAIR_MAX_STEPS_ENV = "FEATURELIFTBENCH_CONTRACT_CLOSURE_REPAIR_MAX_STEPS"
INFRA_RETRY_LIMIT_ENV = "FEATURELIFTBENCH_CONTRACT_CLOSURE_INFRA_RETRY_LIMIT"
INFRA_RETRY_MAX_STEPS_ENV = (
    "FEATURELIFTBENCH_CONTRACT_CLOSURE_INFRA_RETRY_MAX_TRIGGER_STEPS"
)

PUBLIC_CONTRACT_FILE = "PUBLIC_CONTRACT.json"
CASES_DIR = "contract_cases"
WRAPPER_NAME = "flb-contract-check"
LATEST_RESULT_FILE = "contract_closure_latest.json"
FAILURES_FILE = "CONTRACT_CLOSURE_FAILURES.md"
INITIAL_RESULT_FILE = "contract_closure_initial.json"
FINAL_RESULT_FILE = "contract_closure_final.json"
AUDIT_FILE = "contract_closure_phase.json"

PUBLIC_CONTRACT_SCHEMA = "featureliftbench.public_contract.v1"
CHECK_SCHEMA = "featureliftbench.contract_closure_check.v1"
AUDIT_SCHEMA = "featureliftbench.contract_closure_phase.v1"
GENERATOR_VERSION = "contract_closure_gate.v4"
LITE_POLICY_VERSION = "contract_closure_gate_lite.v2.1"
LITE_V1_POLICY_VERSION = "contract_closure_gate_lite.v1-frozen.1"
V3_POLICY_VERSION = "contract_closure_gate.v3"

DEFAULT_CASE_TIMEOUT_SECONDS = 30
DEFAULT_REPAIR_ROUNDS = 1
DEFAULT_REPAIR_TIMEOUT_SECONDS = 900
DEFAULT_REPAIR_MAX_STEPS = 20
DEFAULT_LITE_PRIMARY_TOKEN_LIMIT = 2_000_000
DEFAULT_LITE_REPAIR_TOKEN_LIMIT = 200_000
DEFAULT_LITE_PRIMARY_MAX_STEPS = 45
DEFAULT_LITE_REPAIR_MAX_STEPS = 5
DEFAULT_LITE_V1_REPAIR_TOKEN_LIMIT = 500_000
DEFAULT_LITE_V1_REPAIR_MAX_STEPS = 10
DEFAULT_LITE_INFRA_RETRY_LIMIT = 1
DEFAULT_LITE_INFRA_RETRY_MAX_TRIGGER_STEPS = 8
DEFAULT_V3_MAX_CASES = 3
DEFAULT_LITE_MAX_REPAIR_FAILURES = 3
DEFAULT_LITE_MAX_MISSING_APIS = 2
